---
- name: Restart unattended upgrades service
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted

- name: Restart TLP service
  ansible.builtin.service:
    name: tlp
    state: restarted
  listen: restart tlp
