---
- name: Set up Jellyfin
  when: jellyfin_enabled is true
  vars:
    jellyfin_authorization_header: >-
      MediaBrowser Client="Jellyfin Web", Device="Ansible", Version="10.9.7"
      {{ jellyfin_auth_token | ternary(', Token="' + jellyfin_auth_token + '"', '') }}
  block:

    - name: Install required packages
      ansible.builtin.package:
        name:
          - acl               # For setting media library permissions using ACLs
          - python3-requests  # For jellysetup.py script
        state: present

    - name: Add Jellyfin user
      ansible.builtin.user:
        name: jellyfin
        groups:
          - video
          - render
        uid: 896
        system: true
        shell: /sbin/nologin

    # Use ACLs to allow Jellyfin to access media files. This allows us to use
    # one of the NAS shares as the media directory, and have Jellyfin access
    # the files without having to change the owner or run as root.
    - name: Set permissions on Jellyfin media directory
      ansible.posix.acl:
        path: "{{ jellyfin_media_dir }}"
        entity: jellyfin
        etype: user
        permissions: rwX
        default: true
        recurse: true
        recalculate_mask: mask
        state: present

    - name: Create metadata directory for media
      ansible.builtin.file:
        path: "{{ jellyfin_media_dir }}/metadata"
        state: directory
        owner: jellyfin
        mode: '0700'

    - name: Check if Jellyfin configuration directory exists
      ansible.builtin.stat:
        path: "{{ jellyfin_data_dir }}/config"
      register: config_dir
      changed_when: false

    - name: Create Jellyfin data directory
      ansible.builtin.file:
        path: "{{ jellyfin_data_dir }}"
        state: directory
        owner: jellyfin
        mode: '0700'

    - name: Start Jellyfin
      # when: false
      community.docker.docker_container:
        name: jellyfin
        image: lscr.io/linuxserver/jellyfin:latest
        restart_policy: unless-stopped
        volumes:
          - "{{ jellyfin_media_dir }}:/media"
          - "{{ jellyfin_data_dir }}/config:/config"
        tmpfs:
          - /config/transcodes
          - /config/cache
          - /config/data/transcodes
        devices: >-
          {{ jellyfin_enable_vaapi | ternary([
            '/dev/dri/card0:/dev/dri/card0',
            '/dev/dri/renderD128:/dev/dri/renderD128',
          ], []) }}
        env:
          PUID: '896' # jellyfin user
          UMASK: '002'
          DOCKER_MODS: ghcr.io/kdkasad/docker-mods/jellyfin-jellyscrub
          JELLYFIN_PublishedServerUrl: "https://{{ jellyfin_routing.subdomain }}.{{ general.domain }}"
        network_mode: host # Use host networking to allow Jellyfin to use DLNA
        labels:
          traefik.enable: "{{ jellyfin_routing.enabled | ternary('true', 'false') }}"
          traefik.http.routers.jellyfin.rule: Host(`{{ jellyfin_routing.subdomain }}.{{ general.domain }}`)
          traefik.http.routers.jellyfin.entrypoints: websecure
          traefik.http.services.jellyfin.loadbalancer.server.port: '8096'
        healthcheck:
          test: ["CMD-SHELL", "curl -fs http://localhost:8096/health"]

    - name: Render Jellyfin setup script
      when: not config_dir.stat.exists
      ansible.builtin.template:
        src: jellysetup.py
        dest: /tmp/jellysetup.py
        mode: '0750'
        owner: jellyfin
        group: jellyfin

    - name: Wait for Jellyfin to start
      ansible.builtin.wait_for:
        host: localhost
        port: 8096
        timeout: 60

    - name: Run Jellyfin setup script
      when: not config_dir.stat.exists
      ansible.builtin.command:
        cmd: python3 /tmp/jellysetup.py
      changed_when: true

    - name: Delete Jellyfin setup script
      when: not config_dir.stat.exists
      ansible.builtin.file:
        path: /tmp/jellysetup.py
        state: absent

- name: Disable Jellyfin
  when: jellyfin_enabled is false
  block:
    - name: Stop Jellyfin
      community.docker.docker_container:
        name: jellyfin
        state: absent
