---
####################
# General settings #
####################

general:
  # Set the hostname of the server
  hostname: casad

  # Web domain name of the server
  domain: box.kasad.com

  # Set the timezone
  timezone: America/Los_Angeles

  # Only automatically install security updates
  auto_update_packages: security

users:
  worker: worker
  nas: nas

####################
# Storage settings #
####################

storage:

  # Directory in which application data will be stored
  data_dir: /data

  # Directory in which NAS will be mounted
  nas_dir: /nas

  # Directory for Docker images
  docker_dir: /var/lib/docker

  # Define LVM volumes
  vg: pool
  volumes:
    root:
      mount: /
      size: 64G
      fs: ext4

    nas:
      mount: /nas
      size: 50G
      fs: ext4

    data:
      mount: /data
      size: 100G
      fs: ext4

#################
# Samba options #
#################

# See https://github.com/vladgh/ansible-collection-vladgh-samba
samba_guest_account: "{{ users.nas }}"
samba_shares_root: "{{ storage.nas_dir }}"
samba_manage_directories: no
samba_netbios_name: "{{ general.hostname }}"
samba_server_string: Home NAS
samba_wins_support: no
samba_domain_master: no
samba_preferred_master: no
samba_local_master: yes

# Treat unknown users as guests, but treat bad passwords as errors.
# See https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html
samba_map_to_guest: Bad User

samba_shares:
  - name: Dump
    comment: A place for files to go
    public: yes
    writeable: yes

############################
# Minecraft server options #
############################

minecraft_server_enabled: yes
minecraft_server_env:
  # Server properties
  SERVER_PORT: "25565"
  ENFORCE_SECURE_PROFILE: "false"
  ONLINE_MODE: "false"
  ENABLE_COMMAND_BLOCK: "true"
  ENABLE_QUERY: "true"

  # Enable automatically pausing when nobody is online
  EXEC_DIRECTLY: "false"
  ENABLE_AUTOPAUSE: "true"
  MAX_TICK_TIME: "-1" # See https://docker-minecraft-server.readthedocs.io/en/latest/misc/autopause-autostop/autopause/
  AUTOPAUSE_TIMEOUT_EST: "600" # Pause 10 minutes after last player disconnects
  AUTOPAUSE_TIMEOUT_INIT: "60" # Pause 1 minute after startup if inactive

  # Server settings
  TYPE: fabric
  VERSION: "1.20.4"
  INIT_MEMORY: "512M"
  MAX_MEMORY: "4G"

  # For custom datapacks and resource packs from vanillatweaks.net
  # https://vanillatweaks.net/share#<sharecode>
  VANILLATWEAKS_SHARECODE: rIS4z6,IWrn6G # data, resource

  # Mods to download from Modrinth
  # https://modrinth.com/mods/<slug>
  MODRINTH_PROJECTS: |-
    fabric-api
    lithium
    no-chat-reports
    fabrictailor
    coord-finder:beta
    carpet
    worldedit
    image2map

######################
# Authentik settings #
######################

authentik_enabled: yes

# Traefik routing options for Authentik
authentik_routing:
  enabled: true
  subdomain: auth

authentik_env:
  # These first three don't need to be encrypted. It's just so scrapers don't
  # pick up my email and try to spam me or break in.
  AUTHENTIK_EMAIL__FROM: "{{ secret_authentik_email_from }}"
  AUTHENTIK_EMAIL__HOST: "{{ secret_authentik_email_host }}"
  AUTHENTIK_EMAIL__USERNAME: "{{ secret_authentik_email_username }}"

  # This one is actually sensitive and must be encrypted
  AUTHENTIK_EMAIL__PASSWORD: "{{ secret_authentik_email_password }}"

  AUTHENTIK_EMAIL__PORT: 465
  AUTHENTIK_EMAIL__USE_SSL: true
  AUTHENTIK_EMAIL__TIMEOUT: 10

  # PostgreSQL root password
  PG_PASS: "{{ secret_authentik_pg_pass }}"

  # Credentials for the Authentik "akadmin" user during initial setup
  AUTHENTIK_BOOTSTRAP_EMAIL: "{{ secret_authentik_bootstrap_email }}"
  AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ secret_authentik_bootstrap_password }}"

####################
# Traefik settings #
####################

traefik_enabled: true

traefik_ports:
    http: 80
    https: 443

# See https://doc.traefik.io/traefik/https/acme/ for information on how to
# configure the provider and environment variables.
traefik_acme_dns:
  enabled: true
  provider: cloudflare

  # The email doesn't need to be encrypted, but doing so hides it from bots
  # scraping GitHub for credentials.
  email: "{{ secret_letsencrypt_email }}"
  env:
    CF_DNS_API_TOKEN: "{{ secret_cloudflare_dns_api_token }}"

######################
# Tailscale settings #
######################

tailscale_enabled: true

# Subnets to route traffic to
tailscale_routes:
  - "10.0.0.0/24"

tailscale_auth_key: "{{ secret_tailscale_auth_key }}"

###################
# Homarr settings #
###################

homarr_enabled: true
homarr_routing:
  enabled: true
  homepage: true

# OIDC settings for Authentik
homarr_env:
  AUTH_PROVIDER: oidc
  AUTH_OIDC_CLIENT_NAME: Authentik
  AUTH_OIDC_CLIENT_ID: "{{ secret_homarr_oidc_client_id }}"
  AUTH_OIDC_CLIENT_SECRET: "{{ secret_homarr_oidc_client_secret }}"
  AUTH_OIDC_ADMIN_GROUP: Administrators
  AUTH_OIDC_URI: "https://{{ authentik_routing.subdomain | default('auth') }}.{{ general.domain }}/application/o/homarr"
  AUTH_LOGOUT_REDIRECT_URL: "https://{{ authentik_routing.subdomain | default('auth') }}.{{ general.domain }}/application/o/homarr/end-session/"

##################
# Minio settings #
##################

minio_enabled: true

minio_routing:
  enabled: true
  api_subdomain: s3
  ui_subdomain: minio

minio_root_user: "{{ secret_minio_root_user }}"
minio_root_password: "{{ secret_minio_root_password }}"
