---
####################
# General settings #
####################

general:
  # Set the hostname of the server
  hostname: casad

  # Set the timezone
  timezone: America/Los_Angeles

users:
  worker: worker
  nas: nas

####################
# Storage settings #
####################

storage:

  # Directory in which application data will be stored
  data_dir: /data

  # Directory in which NAS will be mounted
  nas_dir: /nas

  # Directory for Docker images
  docker_dir: /var/lib/docker

  # Define LVM volumes
  vg: pool
  volumes:
    root:
      mount: /
      size: 64G
      fs: ext4

    nas:
      mount: /nas
      size: 50G
      fs: ext4

    data:
      mount: /data
      size: 100G
      fs: ext4

#################
# Samba options #
#################

# See https://github.com/vladgh/ansible-collection-vladgh-samba
samba_guest_account: "{{ users.nas }}"
samba_shares_root: "{{ storage.nas_dir }}"
samba_manage_directories: no
samba_netbios_name: "{{ general.hostname }}"
samba_server_string: Home NAS
samba_wins_support: no
samba_domain_master: no
samba_preferred_master: no
samba_local_master: yes

# Treat unknown users as guests, but treat bad passwords as errors.
# See https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html
samba_map_to_guest: Bad User

samba_shares:
  - name: Dump
    comment: A place for files to go
    public: yes
    writeable: yes

############################
# Minecraft server options #
############################

minecraft_server_enabled: yes
minecraft_server_env:
  # Server properties
  SERVER_PORT: "25565"
  ENFORCE_SECURE_PROFILE: "false"
  ONLINE_MODE: "false"
  ENABLE_COMMAND_BLOCK: "true"
  ENABLE_QUERY: "true"

  # Enable automatically pausing when nobody is online
  EXEC_DIRECTLY: "false"
  ENABLE_AUTOPAUSE: "true"
  MAX_TICK_TIME: "-1" # See https://docker-minecraft-server.readthedocs.io/en/latest/misc/autopause-autostop/autopause/
  AUTOPAUSE_TIMEOUT_EST: "600" # Pause 10 minutes after last player disconnects
  AUTOPAUSE_TIMEOUT_INIT: "60" # Pause 1 minute after startup if inactive

  # Server settings
  TYPE: fabric
  VERSION: "1.20.4"
  INIT_MEMORY: "512M"
  MAX_MEMORY: "4G"

  # For custom datapacks and resource packs from vanillatweaks.net
  # https://vanillatweaks.net/share#<sharecode>
  VANILLATWEAKS_SHARECODE: rIS4z6,IWrn6G # data, resource

  # Mods to download from Modrinth
  # https://modrinth.com/mods/<slug>
  MODRINTH_PROJECTS: |-
    fabric-api
    lithium
    no-chat-reports
    fabrictailor
    coord-finder:beta
    carpet
