---
- name: Deploy home server
  hosts: homeserver
  become: true

  roles:
    - role: setup_general
      tags:
        - setup

    - role: setup_disks
      tags:
        - setup
        - nas

    - role: setup_users
      tags:
        - setup
        - nas

    - role: setup_dns
      tags:
        - setup
        - dns

    - role: setup_ssh
      tags:
        - setup
        - ssh

    - role: fail2ban
      tags:
        - fail2ban

    - role: setup_docker
      tags:
        - setup
        - docker

    - role: dnsmasq
      tags:
        - dnsmasq
        - dns

    - role: coredns
      tags:
        - coredns
        - dns

    - role: vladgh.samba.server
      tags:
        - nas

    # This must happen after Samba is installed, because wsdd2.service depends
    # on smbd.service.
    - role: setup_zeroconf
      tags:
        - setup
        - dns

    - role: healthchecksio
      tags:
        - healthcheck

    - role: ddns
      tags:
        - ddns
        - dns

    - role: minecraft_server
      tags:
        - minecraft

    - role: authentik
      tags:
        - authentik

    - role: traefik
      tags:
        - traefik

    - role: tailscale
      tags:
        - tailscale

    - role: homarr
      tags:
        - homarr

    - role: minio
      tags:
        - minio

    - role: bitwarden
      tags:
        - bitwarden

    - role: jellyfin
      tags:
        - jellyfin

    - role: monitoring
      tags:
        - monitoring

    - role: photos_archive
      tags:
        - immich
        - photos_archive

    - role: immich
      tags:
        - immich

    - role: excalidraw
      tags:
        - excalidraw

    - role: egrass_bot
      tags:
        - egrass_bot
        - egrass-bot

    - role: website_ci_enabler
      tags:
        - website-ci-enabler
        - website_ci_enabler

    - role: umami
      tags: [umami]
