---
- name: Deploy home server
  hosts: homeserver
  become: true

  roles:
    - role: setup_general
      tags:
        - setup

    - role: setup_disks
      tags:
        - setup
        - nas

    - role: setup_users
      tags:
        - setup
        - nas

    - role: setup_dns
      tags:
        - setup
        - dns

    - role: setup_ssh
      tags:
        - setup

    - role: setup_docker
      tags:
        - docker

    - role: dnsmasq
      tags:
        - dnsmasq
        - dns

    - role: vladgh.samba.server
      tags:
        - nas

    # This must happen after Samba is installed, because wsdd2.service depends
    # on smbd.service.
    - role: setup_zeroconf
      tags:
        - setup
        - dns

    - role: ddns
      tags:
        - ddns
        - dns

    - role: minecraft_server
      tags:
        - minecraft

    - role: authentik
      tags:
        - authentik

    - role: traefik
      tags:
        - traefik

    - role: tailscale
      tags:
        - tailscale

    - role: homarr
      tags:
        - homarr

    - role: minio
      tags:
        - minio

    - role: bitwarden
      tags:
        - bitwarden

    - role: jellyfin
      tags:
        - jellyfin

    - role: monitoring
      tags:
        - monitoring
