---
- name: Deploy home server
  hosts: homeserver
  become: true

  roles:
    - role: setup-general
      tags:
        - setup

    - role: setup-disks
      tags:
        - setup
        - nas

    - role: setup-users
      tags:
        - setup
        - nas

    - role: setup-ssh
      tags:
        - setup

    - role: setup-docker
      tags:
        - docker

    - role: ddclient
      tags:
        - ddclient

    - role: vladgh.samba.server
      tags:
        - nas

    - role: minecraft-server
      tags:
        - minecraft

    - role: authentik
      tags:
        - authentik

    - role: traefik
      tags:
        - traefik

    - role: tailscale
      tags:
        - tailscale

    - role: homarr
      tags:
        - homarr

    - role: minio
      tags:
        - minio

    - role: bitwarden
      tags:
        - bitwarden
