---
roles:
  - name: geerlingguy.docker
    version: 7.2.0

collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: community.docker
  - name: community.general

  - name: vladgh.samba
    version: 3.4.0
