---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ general.hostname }}"

- name: Set timezone
  community.general.timezone:
    name: "{{ general.timezone }}"

# TODO: Extract Avahi setup to a separate setup-network role
- name: Install network discovery service daemons
  ansible.builtin.package:
    name:
      - avahi-daemon # for mDNS
      - wsdd2 # for WSD and LLMNR
    state: present

- name: Enable and start Avahi daemon
  ansible.builtin.service:
    name: avahi-daemon
    enabled: yes
    state: started

- name: Enable and start WSDD
  ansible.builtin.service:
    name: wsdd2
    enabled: yes
    state: started

- name: Configure Avahi daemon
  ansible.builtin.template:
    src: templates/avahi-daemon.conf
    dest: /etc/avahi/avahi-daemon.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Avahi daemon

- name: Configure unattended upgrades
  when: ansible_facts['distribution'] == "Debian" and general.auto_update_packages != "none"
  block:
    - name: Install unattended upgrades package
      ansible.builtin.package:
        name: unattended-upgrades
        state: present

    - name: Copy unattended upgrades configuration file
      ansible.builtin.template:
        src: templates/unattended-upgrades.conf
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify: Restart unattended upgrades service


    - name: Enable and start unattended upgrades service
      ansible.builtin.service:
        name: unattended-upgrades
        enabled: yes
        state: started

- name: Disable unattended upgrades
  when: ansible_facts['distribution'] == "Debian" and general.auto_update_packages == "none"
  ansible.builtin.service:
    name: unattended-upgrades
    enabled: no
    state: stopped
