---
tailscale_enabled: false
tailscale_auth_key: "{{ undef(hint='Tailscale auth key must be set') }}"
tailscale_data_dir: "{{ storage.data_dir }}/tailscale"
tailscale_routes: []

# Version/tag of the tailscale/tailscale image to use
tailscale_tag: v1.20
