---
monitoring_enabled: true

monitoring_data_dir: "{{ storage.data_dir }}/monitoring"
monitoring_prometheus_data_dir: "{{ monitoring_data_dir }}/prometheus"
monitoring_grafana_data_dir: "{{ monitoring_data_dir }}/grafana"

monitoring_prometheus_routing_enabled: true
monitoring_prometheus_routing_subdomain: "prometheus"
monitoring_prometheus_routing_private: true

monitoring_grafana_routing_enabled: true
monitoring_grafana_routing_subdomain: "grafana"
monitoring_grafana_routing_private: true

monitoring_grafana_sso: false
monitoring_grafana_sso_only: true
monitoring_grafana_client_id: "{{ undef() }}"
monitoring_grafana_client_secret: "{{ undef() }}"

monitoring_node_exporter_args:
  - --collector.systemd
