---
monitoring_enabled: true

monitoring_data_dir: "{{ storage.data_dir }}/monitoring"
monitoring_prometheus_data_dir: "{{ monitoring_data_dir }}/prometheus"
monitoring_grafana_data_dir: "{{ monitoring_data_dir }}/grafana"
monitoring_loki_data_dir: "{{ monitoring_data_dir }}/loki"
monitoring_promtail_data_dir: "{{ monitoring_data_dir }}/promtail"

# Version/tag of the quay.io/prometheus/prometheus image to use
monitoring_prometheus_tag: v2.53.1
monitoring_grafana_tag: "11.1.0"
monitoring_grafana_image_renderer_tag: "3.11.1"
monitoring_cadvisor_tag: v0.49.1
monitoring_loki_tag: "3.1.0"  # Be sure to also update the Loki driver in the setup_docker role
monitoring_promtail_tag: "{{ monitoring_loki_tag }}"

monitoring_prometheus_routing_enabled: true
monitoring_prometheus_routing_subdomain: prometheus
monitoring_prometheus_routing_private: true

monitoring_grafana_routing_enabled: true
monitoring_grafana_routing_subdomain: grafana
monitoring_grafana_routing_private: true

monitoring_grafana_sso: false
monitoring_grafana_sso_only: true
monitoring_grafana_client_id: "{{ undef() }}"
monitoring_grafana_client_secret: "{{ undef() }}"

monitoring_grafana_smtp_enabled: no
monitoring_grafana_smtp_host: "{{ undef() }}"
monitoring_grafana_smtp_user: "{{ undef() }}"
monitoring_grafana_smtp_password: "{{ undef() }}"
monitoring_grafana_smtp_from_address: >-
  no-reply@{{ monitoring_grafana_routing_subdomain }}.{{ general.domain }}
monitoring_grafana_smtp_from_name: Grafana
monitoring_grafana_send_welcome_email: yes

monitoring_node_exporter_args:
  - --collector.systemd
  - --collector.processes

# Enable/disable metrics collection from specific services
monitoring_scrape_authentik: yes
monitoring_scrape_jellyfin: yes
monitoring_scrape_minio: yes
monitoring_scrape_traefik: yes

# Extra scrape configs for Prometheus.
monitoring_prometheus_extra_scrape_configs: []
