http:
  routers:
    landing_redirect:
      rule: Host(`{{ general.domain }}`) && Path(`/`)
      service: noop@internal
      middlewares:
        - redirect_to_authentik

  middlewares:
    redirect_to_authentik:
      redirectRegex:
        regex: ".*"
        replacement: "https://{{ authentik_routing.subdomain | default('authentik') }}.{{ general.domain }}/"
