---
# Needed to get Wi-Fi card working
- name: Install kernel and iwlwifi firmware from backports
  block:
    - name: Enable non-free-firmware from backports
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/backports.list
        content: |
          deb http://deb.debian.org/debian bookworm-backports main non-free-firmware
        owner: root
        group: root
        mode: '0644'
      register: add_backports

    - name: Install kernel and iwlwifi firmware from backports
      ansible.builtin.apt:
        package:
          - linux-image-amd64
          - firmware-iwlwifi
          - firmware-intel-graphics
        default_release: bookworm-backports
        update_cache: "{{ add_backports.changed }}"

- name: Configure systemd-networkd
  block:
    - name: Create systemd-networkd configuration files
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/etc/systemd/network/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - 10-bridge.netdev
        - 20-bridge.network
        - 20-enp1s0.network
        - 90-eth.network
      notify: reload systemd-networkd

    - name: Disable legacy networking
      ansible.builtin.service:
        name: networking.service
        state: stopped
        enabled: false

    - name: Enable systemd-networkd
      ansible.builtin.service:
        name: systemd-networkd.service
        state: started
        enabled: true

- name: Configure hostapd
  block:
    - name: Render hostapd configuration
      ansible.builtin.template:
        src: "hostapd.{{ item }}.conf"
        dest: "/etc/hostapd/{{ item }}.conf"
        owner: root
        group: root
        mode: '0600'
      loop:
        - wlan0

    - name: Enable/disable hostapd
      ansible.builtin.service:
        name: hostapd@{{ item }}.service
        state: "{{ setup_network_wifi_ap_enabled | ternary('started', 'stopped') }}"
        enabled: "{{ setup_network_wifi_ap_enabled }}"
      loop:
        - wlan0

- name: Configure firewall
  ansible.builtin.template:
    src: firewall.nft
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0600'
  notify: reload nftables

- name: Start & enable nftables.service
  ansible.builtin.service:
    name: nftables.service
    state: started
    enabled: true

- name: Install Python libraries
  ansible.builtin.package:
    name: python3-prometheus-client
    state: present

- name: Render Python script
  ansible.builtin.template:
    src: prometheus_nftables_exporter.py
    dest: /usr/local/bin/prometheus_nftables_exporter.py
    owner: root
    group: root
    mode: '0755'
  notify: restart prometheus-nftables-exporter

- name: Render systemd service
  ansible.builtin.template:
    src: prometheus-nftables-exporter.service
    dest: /etc/systemd/system/prometheus-nftables-exporter.service
    owner: root
    group: root
    mode: '0644'
  notify: restart prometheus-nftables-exporter

- name: Start & enable prometheus-nftables-exporter.service
  ansible.builtin.service:
    name: prometheus-nftables-exporter.service
    state: started
    enabled: true
