name: egrass-bot

networks:
  subway:
    external: true
    name: subway

services:
  bot:
    image: ghcr.io/kdkasad/egrass-bot:edge
    pull_policy: always
    restart: unless-stopped
    volumes:
      - "{{ egrass_bot_data_dir }}:/var/lib/bot"
    environment:
      TZ: America/Indianapolis
      DISABLED_FEATURES: "{{ egrass_bot_disabled_features | join(',') }}"
      DATABASE_FILE: data.sqlite3
    env_file: secrets.env
    networks:
      - subway
    labels:
      traefik.enable: "true"
      traefik.http.routers.egrass-bot.rule: Host(`egrass-bot.{{ general.domain }}`)
      traefik.http.routers.egrass-bot.entrypoints: websecure
      traefik.http.services.egrass-bot.loadbalancer.server.port: "80"
