---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ general.hostname }}"

- name: Set timezone
  community.general.timezone:
    name: "{{ general.timezone }}"

- name: Configure unattended upgrades
  when: ansible_facts['distribution'] == "Debian" and general.auto_update_packages != "none"
  block:
    - name: Install unattended upgrades package
      ansible.builtin.package:
        name: unattended-upgrades
        state: present

    - name: Copy unattended upgrades configuration file
      ansible.builtin.template:
        src: templates/unattended-upgrades.conf
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify: Restart unattended upgrades service


    - name: Enable and start unattended upgrades service
      ansible.builtin.service:
        name: unattended-upgrades
        enabled: yes
        state: started

- name: Disable unattended upgrades
  when: ansible_facts['distribution'] == "Debian" and general.auto_update_packages == "none"
  ansible.builtin.service:
    name: unattended-upgrades
    enabled: no
    state: stopped
