---
- name: Set up Tailscale
  when: tailscale_enabled is true
  block:
    - name: Create data directory
      ansible.builtin.file:
        name: "{{ item }}"
        state: directory
        owner: "root"
        group: "root"
        mode: '0700'
        recurse: false
      with_items:
        - "{{ tailscale_data_dir }}"

    - name: Render sysctl drop-in file
      ansible.builtin.template:
        src: 99-tailscale.conf
        dest: /etc/sysctl.d/99-tailscale.conf
        mode: '0644'
      notify: reload sysctl

    - name: Start Tailscale container
      community.docker.docker_container:
        name: tailscale
        image: ghcr.io/tailscale/tailscale:{{ tailscale_tag }}
        pull: always
        image_name_mismatch: recreate
        restart_policy: unless-stopped
        env:
          TS_AUTHKEY: "{{ tailscale_auth_key | mandatory }}"
          TS_USERSPACE: "false"
          TS_STATE_DIR: /var/lib/tailscale
          TS_HOSTNAME: "{{ general.hostname }}"
          TS_ROUTES: "{{ tailscale_routes | map('ansible.utils.ipaddr') | join(',') | default(omit) }}"
          TS_EXTRA_ARGS: --advertise-exit-node
          TS_DEBUG_FIREWALL_MODE: nftables
        network_mode: host
        volumes:
          - "{{ tailscale_data_dir }}:/var/lib/tailscale"
        devices:
          - /dev/net/tun
        capabilities:
          - net_admin
          - sys_module

- name: Stop Tailscale
  when: tailscale_enabled is false
  community.docker.docker_container:
    name: tailscale
    state: absent
