---
# Configure Docker daemon options. These are merged with the default options
# below and used to create /etc/docker/daemon.json.
setup_docker_daemon_options: {}

# Default options for Docker daemon. Use the `setup_docker_daemon_options`
# variable to override these.
setup_docker_default_daemon_options:
  # Set the directory for Docker to store images, logs, etc. in.
  data-root: "{{ storage.docker_dir | default('/var/lib/docker') }}"

  # In order for Promtail to read container logs, we must use the json-file
  # logging driver. The Loki logging driver plugin exists, but it causes issues
  # when trying to stop/restart the Loki container.
  log-driver: json-file
  log-opts:
    tag: "{{ '{{' }}.Name{{ '}}' }}"
    max-size: 10m
    max-file: "1"
