---
# Enable/disable dnsmasq
dnsmasq_enabled: false

# Set data directory
dnsmasq_data_dir: "{{ storage.data_dir }}/dnsmasq"

# Set the port to listen on
dnsmasq_port: 53

# Use Cloudflare's DNS servers by default
dnsmasq_upstream_dns_servers: "{{ general.upstream_dns_servers | mandatory }}"

# Domains to treat as LAN-local
dnsmasq_local_domain_suffix: local
dnsmasq_local_domains:
  - "{{ dnsmasq_local_domain_suffix }}"
  - localdomain
  - lan

# Custom A/AAAA DNS records
dnsmasq_custom_hosts:
  - name: "{{ general.domain }}"
    ip: "{{ ansible_default_ipv4.address }}"

# Version/tag of the ghcr.io/dockur/dnsmasq image to use
dnsmasq_tag: "2.90"
