---
# Enable/disable dnsmasq
dnsmasq_enabled: false

# Set data directory
dnsmasq_data_dir: "{{ storage.data_dir }}/dnsmasq"

# Use Cloudflare's DNS servers by default
dnsmasq_upstream_dns_servers:
  - '1.1.1.1'
  - '1.0.0.1'
  - '2606:4700:4700::1111'
  - '2606:4700:4700::1001'

# Domains to treat as LAN-local
dnsmasq_local_domain_suffix: local
dnsmasq_local_domains:
  - "{{ dnsmasq_local_domain_suffix }}"
  - localdomain
  - lan

# Custom A/AAAA DNS records
dnsmasq_custom_hosts:
  - name: "{{ general.domain }}"
    ip: "{{ ansible_default_ipv4.address }}"

# Version/tag of the ghcr.io/dockur/dnsmasq image to use
dnsmasq_tag: "2.90"
