---
- name: Set up egrass-bot
  when: egrass_bot_enabled is true
  block:
    - name: Create data directory
      ansible.builtin.file:
        name: "{{ egrass_bot_data_dir }}"
        state: directory
        owner: "{{ users.worker }}"
        group: "{{ users.worker }}"
        mode: '0755'

    - name: Start egrass_bot
      community.docker.docker_container:
        name: egrass-bot
        image: ghcr.io/kdkasad/egrass-bot:{{ egrass_bot_tag }}
        state: started
        restart_policy: unless-stopped
        volumes:
          - "{{ egrass_bot_data_dir }}:/var/lib/bot"
        env:
          DISCORD_BOT_TOKEN: "{{ egrass_bot_token }}"
          DISCORD_CLIENT_ID: "{{ egrass_bot_client_id }}"

- name: Disable egrass-bot
  when: egrass_bot_enabled is false
  block:
    - name: Stop egrass-bot
      community.docker.docker_container:
        name: egrass-bot
        state: absent
