---
- name: Set up egrass-bot
  when: egrass_bot_enabled is true
  block:
    - name: Create data directory
      ansible.builtin.file:
        name: "{{ egrass_bot_data_dir }}"
        state: directory
        owner: "{{ users.worker }}"
        group: "{{ users.worker }}"
        mode: '0755'

    - name: Render templates
      ansible.builtin.template:
        src: "templates/{{ item }}"
        dest: "{{ egrass_bot_data_dir }}/{{ item }}"
        owner: "{{ users.worker }}"
        group: "{{ users.worker }}"
        mode: '0644'
      loop:
        - docker-compose.yml
        - secrets.env

    - name: Start egrass-bot
      become: true
      become_user: "{{ users.worker }}"
      community.docker.docker_compose_v2:
        project_src: "{{ egrass_bot_data_dir }}"
        wait: true


- name: Disable egrass-bot
  when: egrass_bot_enabled is false
  block:
    - name: Stop egrass-bot
      community.docker.docker_compose_v2:
        project_src: "{{ egrass_bot_data_dir }}"
        state: absent
