---
minio_enabled: false

minio_routing:
  enabled: true
  api_subdomain: s3
  ui_subdomain: minio

minio_data_dir: "{{ storage.data_dir }}/minio"

minio_container:
  image: quay.io/minio/minio
  tag: RELEASE.2024-07-16T23-46-41Z

minio_root_user: "{{ undef(hint='You must set the Minio root username') }}"
minio_root_password: "{{ undef(hint='You must set the Minio root password') }}"

minio_env: {}
