---
- name: Set up dnsmasq
  when: dnsmasq_enabled is true
  block:
    - name: Create data directory
      ansible.builtin.file:
        name: "{{ dnsmasq_data_dir }}"
        state: directory
        owner: "{{ users.worker }}"
        group: "{{ users.worker }}"
        mode: '0750'

    - name: Render configuration file
      ansible.builtin.template:
        src: dnsmasq.conf
        dest: "{{ dnsmasq_data_dir }}/dnsmasq.conf"
        owner: "{{ users.worker }}"
        group: "{{ users.worker }}"
        mode: '0640'
      register: dnsmasq_config

    - name: Start dnsmasq
      community.docker.docker_container:
        name: dnsmasq
        image: ghcr.io/dockur/dnsmasq:{{ dnsmasq_tag }}
        pull: always
        image_name_mismatch: recreate
        state: started
        restart: "{{ dnsmasq_config.changed }}"
        restart_policy: unless-stopped
        ports:
          - "{{ dnsmasq_port }}:{{ dnsmasq_port }}/udp"
          - "{{ dnsmasq_port }}:{{ dnsmasq_port }}/tcp"
        volumes:
          - "{{ dnsmasq_data_dir }}/dnsmasq.conf:/etc/dnsmasq.conf:ro"
        capabilities:
          - NET_ADMIN
        networks_cli_compatible: false
        networks:
          - name: subway

- name: Disable dnsmasq
  when: dnsmasq_enabled is false
  block:
    - name: Stop dnsmasq
      community.docker.docker_container:
        name: dnsmasq
        state: absent
