---
- name: Start Traefik
  when: traefik_enabled is true
  block:
    - name: Create Traefik Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ users.worker }}"
        group: "{{ users.worker }}"
        mode: '0750'
      with_items:
        - "{{ traefik_data_dir }}"
        - "{{ traefik_data_dir }}/letsencrypt"
        - "{{ traefik_data_dir }}/dynamic"

    - name: Render main Traefik config file
      ansible.builtin.template:
        src: traefik.yml.j2
        dest: "{{ traefik_data_dir }}/traefik.yml"
        owner: "{{ users.worker }}"
        group: "{{ users.worker }}"
        mode: '0640'
      register: template_config

    - name: Render Traefik dynamic configuration files
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ traefik_data_dir }}/dynamic/{{ item | basename }}"
        owner: "{{ users.worker }}"
        group: "{{ users.worker }}"
        mode: '0640'
      with_fileglob:
        - templates/dynamic/*.yml

    - name: Traefik Docker Container
      community.docker.docker_container:
        name: traefik
        image: traefik:{{ traefik_tag }}
        pull: always
        image_name_mismatch: recreate
        recreate: "{{ template_config is changed }}"
        restart_policy: unless-stopped
        ports:
          - "80:80"
          - "443:443"
        expose:
          - "{{ traefik_ports.metrics | default(8090) }}"
        volumes:
          - "{{ traefik_data_dir }}/traefik.yml:/etc/traefik/traefik.yml:ro"
          - "{{ traefik_data_dir }}/letsencrypt:/letsencrypt:rw"
          - "{{ traefik_data_dir }}/dynamic:/etc/traefik/dynamic:rw"
          - "/var/run/docker.sock:/var/run/docker.sock:ro"
        env: "{{ traefik_acme_dns.env | mandatory }}"
        networks_cli_compatible: false
        networks:
          - name: subway

- name: Stop Traefik
  when: traefik_enabled is false
  block:
    - name: Stop Traefik
      community.docker.docker_container:
        name: "{{ traefik_container_name }}"
        state: absent
