---
- name: Set up Authentik
  when: authentik_enabled is true
  block:
    - name: Create parent data directories
      ansible.builtin.file:
        name: "{{ authentik_data_dir }}/{{ item }}"
        state: directory
        # Authentik's containers require UID/GID of 1000 to be able to write to
        # the mounted volumes.
        # TODO: Use UID namespaces/mapping to make this more secure.
        owner: "1000"
        group: "1000"
        mode: '0755'
        recurse: false
      with_items:
        - server/media
        - server/custom-templates
        - worker/media
        - worker/certs
        - worker/custom-templates

    - name: Create docker-compose.yml file
      ansible.builtin.template:
        src: templates/docker-compose.yml
        dest: "{{ authentik_data_dir }}/docker-compose.yml"
        owner: "{{ users.worker }}"
        group: "{{ users.worker }}"
        mode: '0400'

    - name: Create .env file
      ansible.builtin.template:
        src: templates/env
        dest: "{{ authentik_data_dir }}/.env"
        owner: "{{ users.worker }}"
        group: "{{ users.worker }}"
        mode: '0400'

    - name: Start Authentik stack
      become: true
      become_user: "{{ users.worker }}"
      community.docker.docker_compose_v2:
        project_src: "{{ authentik_data_dir }}"
        wait: true

- name: Stop Authentik
  when: authentik_enabled is false
  block:
    - name: Check for existing Authentik data directory
      ansible.builtin.stat:
        path: "{{ authentik_data_dir }}/docker-compose.yml"
      register: authentik_dir_check

    - name: Stop Authentik stack
      when: authentik_dir_check.stat.exists
      community.docker.docker_compose_v2:
        project_src: "{{ authentik_data_dir }}"
        state: absent
