---
- name: Restart node-exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted

- name: Reload Prometheus configuration
  community.docker.docker_container_exec:
    container: prometheus
    command: kill -HUP 1  # Send SIGHUP to Prometheus, which runs as PID 1
  changed_when: true

- name: Restart Grafana container
  community.docker.docker_container:
    name: grafana
    state: started
    restart: yes
