---
- name: Restart Prometheus container
  community.docker.docker_container:
    name: prometheus
    state: started
    restart: yes

- name: Restart node-exporter
  ansible.builtin.service:
    name: prometheus-node-exporter
    state: restarted
