services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    pull_policy: always
    user: "{{ worker_uid }}"
    restart: unless-stopped
    volumes:
      - "{{ monitoring_prometheus_data_dir }}/prometheus.yml:/etc/prometheus.yml:ro"
      - "{{ monitoring_prometheus_data_dir }}/data:/prometheus"
    labels:
      traefik.enable: "{{ monitoring_prometheus_routing_enabled | ternary('true', 'false') }}"
      traefik.http.routers.prometheus.rule: "\
        Host(`{{ monitoring_prometheus_routing_subdomain }}.{{ general.domain }}`)
        {% if monitoring_prometheus_routing_private %}
        && (
        ClientIP(`{{ ansible_default_ipv4.network | ansible.utils.ipsubnet(ansible_default_ipv4.prefix) }}`)
        || ClientIP(`fe80::/10`)
        )
        {% endif %}"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"

  node_exporter:
    container_name: prometheus-node-exporter
    image: quay.io/prometheus/node-exporter:latest
    pull_policy: always
    user: "{{ worker_uid }}"
    restart: unless-stopped
    command:
      - "--path.rootfs=/host"
    pid: host
    # network_mode: host
    volumes:
      - "/:/host:ro,rslave"
