server:
  http_listen_port: 80
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki/loki/api/v1/push

scrape_configs:
  # - job_name: system
  #   static_configs:
  #   - targets:
  #       - localhost
  #     labels:
  #       job: varlogs
  #       __path__: /var/log/*log
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      labels:
        job: journal
    relabel_configs:
      - source_labels:
          - __journal__systemd_unit
        target_label: systemd_unit
      - source_labels:
          - __journal__hostname
        target_label: nodename
      - source_labels:
          - __journal_syslog_identifier
        target_label: syslog_identifier
